### ISSUE TITLE
Formatter breaks lines at 110 length, regardless of IntelliJ editor setting

### ISSUE THREAD

**Issue by arberg** [ant-druha/intellij-powershell#103]
Using plugin version 2.0.10.
If I disable the plugin, the problem disappears. 

Typing on a line in a .ps1 file above 110 chars causes intelliJ to break the line and ruining the code (the code becomes incorrect).

**Comment by ForNeVeR** [comment]
Could you please share the steps to reproduce the issue? Here's what I've tried so far:
1. Set the **Hard wrap at: 150** and **Ensure right margin is not exceeded** in the PowerShell code style settings:
   
<img width="573" alt="image" src="https://github.com/ant-druha/intellij-powershell/assets/92793/238ee620-ebad-4ffb-9141-399e9275ab50">

2. Enter the following text in a PowerShell file (148 chars)
   ```powershell
   foo -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a -a a
   ```

3. Invoke the **Reformat code** (`Ctrl+Alt+L` in the IntelliJ keymap on Windows).

The code wasn't wrapped after that. But if I add a few characters (to exceed the 150-character limit), then it gets wrapped on reformat.

Am I doing it correctly? Is there something I miss?
