### ISSUE TITLE
Input from read-host does not work when script executed with run configuration in intellij

### ISSUE THREAD

**Issue by stewart-anderson** [ant-druha/intellij-powershell#106]
I have a powershell script which I requires some input from the user (secure password).  When I run the script in a powershell terminal it runs fine.  

However when in a run configuration under intellij, the prompt is not visible and entering some value at the runtime, has no effect.  Same issue with a simple read-host

Tried faking a sh runner but that fails with other errors. (shell related) 

Discussed with jetbrains support and they asked me to file an issue here.

**Comment by HeXDeMoN** [comment]
Unfortunately a known issue , see this issue - https://github.com/ant-druha/intellij-powershell/issues/32

**Comment by ForNeVeR** [comment]
While still clunky, it works in modern versions of the plugin.

I'll open an issue on the improvements (e.g. the input is weird, not being masked and is duplicated in the PowerShell window).

**Comment by ForNeVeR** [comment]
Follow-up: #154.
