### ISSUE TITLE
Figure out how we use Plaster

### ISSUE THREAD

**Issue by ForNeVeR** [ant-druha/intellij-powershell#133]
Among other things, we bundle [Plaster](https://github.com/PowerShellOrg/Plaster), a PowerShell template engine.

I cannot figure out if we use it somehow, though. We seemingly pass the directory with all our modules to PSES, but what happens next? I can't find any actions that invoke Plaster in our code, or in PSES, for that matter.

@ant-druha, maybe you remember?

**Comment by ForNeVeR** [comment]
https://github.com/search?q=repo%3APowerShell%2FPowerShellEditorServices%20plaster&type=code

PSES seems to be able to load Plaster by itself if required.

But do we invoke any commands that require it? So far it seems no.

**Comment by ant-druha** [comment]
>@ant-druha, maybe you remember?

AFAIR I only included it b/c it was bundled with PSES. As I see, it uses it for the creation of new PS modules, but it is not implemented in this PowerShell plugin.

**Comment by ForNeVeR** [comment]
Ok, thanks, consider it resolved.
