### ISSUE TITLE
Migrate to PowerShell Core by default?

### ISSUE THREAD

**Issue by ForNeVeR** [ant-druha/intellij-powershell#176]
Currently, the plugin prefers classic PowerShell if both PowerShell and PowerShell Core are available (see `com.intellij.plugin.powershell.ide.run.PSExecutionUtilKt#findPsExecutable`).

We should figure out if we it's safe to migrate to Core version by default.

My opinion is that if a person has explicitly installed the Core version, then it's likely they did that for a reason and want to use it: otherwise, why would they install it?

**Comment by andrewimcclement** [comment]
If it is decided that this isn't a good idea, an alternative would be to provide a setting for the _default_ powershell path to use for scripts. (I'm assuming that this would be possible.) Of course, simply switching the default to PSCore is likely sufficient for most people, so that would be the simpler solution.

**Comment by ForNeVeR** [comment]
You can already switch the currently used PowerShell executable in the plugin settings. pwsh is expected to be fully supported, I use it myself. (Though I have to admit that my usage of script run configs may be lower than of some other features.)

**Comment by andrewimcclement** [comment]
Do you mean by editing the Run configuration template for PowerShell to point at the PSCore path? Or is there a more obvious setting somewhere? (I'm not entirely sure I know where to find the right settings).

**Comment by ForNeVeR** [comment]
I mean this setting, **PowerShell executable path**:
<img width="775" alt="image" src="https://github.com/ant-druha/intellij-powershell/assets/92793/ac89a973-bdb1-4a28-a583-2074f6491d4d">

Does it not work?
