### ISSUE TITLE
New Feature Request: Support for Debugging

### ISSUE THREAD

**Issue by moossenm** [ant-druha/intellij-powershell#180]
Hi,

I am just wondering why there is no support for debugging Powershell-Scripts.
Or is there anything special to configure? Google did help with this.
I am wondering that nobody else seems to miss the debugging feature...
I am using meanwhile Microsoft Visual Studio Code for PS bebugging.

many thanks
Michael

**Comment by ForNeVeR** [comment]
> I am just wondering why there is no support for debugging Powershell-Scripts.

The only reason is that debugger implementation is challenging, and thus the debugger wasn't implemented in the plugin _so far_. There are plans to implement it (I would like to tackle it eventually).

Closing as duplicate as #19.

I've also updated the title of that issue, for people to more easily find it.
