### ISSUE TITLE
Debug PowerShell scripts

### ISSUE THREAD

**Issue by delaman** [ant-druha/intellij-powershell#19]
plugin version: v2.0.1

The plugin does not support debugging a powershell script.  Please add the ability to step through a powershell script.

**Comment by stenci** [comment]
Please add debugging with PowerShell.
I like PyCharm much better than VSCode, but I need to go to VSCode for PowerShell because there is no debugging here.

**Comment by Acestus** [comment]
I would like to debug PowerShell in Intellij so I do not need to use VScode

**Comment by ursmeili** [comment]
I also miss this feature every day.

**Comment by stewart-anderson** [comment]
This gets my vote.  I want to be able to fully execute/debug  poweshell, in the IDE. 

TA

**Comment by ForNeVeR** [comment]
This is one of the medium-sized projects I'd like us to eventually tackle in this plugin. No promises, yet.

**Comment by SeanFeldman** [comment]
Using VSCode to get the job done. As I'm spending my time predominantly in Rider, would love to be able to debug PowerShell without leaving Rider.

**Comment by ForNeVeR** [comment]
Good news, everyone: we are releasing a new version with debugger soon (maybe in a day or two).

Thanks to @Fantoom for helping on that!
