### ISSUE TITLE
Consider renaming repo to intellij-powershell?

### ISSUE THREAD

**Issue by TylerLeonhardt** [ant-druha/intellij-powershell#23]
We have:

https://github.com/PowerShell/vscode-powershell
https://github.com/yatli/coc-powershell (for vim)
https://github.com/daviwil/ide-powershell (for atom)

It'd be cool to have this repo follow that 😃

Totally not required, but might be nice for alignment.

**Comment by ant-druha** [comment]
Thanks for suggestion! Done! 🙂
