### ISSUE TITLE
Code folding does not apply to Powershell files

### ISSUE THREAD

**Issue by malclear** [ant-druha/intellij-powershell#25]
I've configured Code Folding in Rider but none of the settings appear to apply to Powershell, nor do any obvious places where folding could apply show as being fold-able.
It does work in my IDE for other languages, just not for Powershell using this plug-in.

**Comment by ant-druha** [comment]
Thank you for your request. Please note that you can fold any custom block of code manually: https://www.jetbrains.com/help/idea/working-with-source-code.html#80ab4aae

**Comment by ForNeVeR** [comment]
Fixed by #48, available since v2.0.5.
