### ISSUE TITLE
Please change the dependency PR notification for your project.

### ISSUE THREAD

**Issue by hubuk** [ant-druha/intellij-powershell#251]
An automated PR like this one: https://github.com/ant-druha/intellij-powershell/pull/244 sends unwanted notifications to all the people mentioned in the original Release Notes. Please consider changes in your workflows or github-actions. Maybe a link to original Release Notes in PR instead of copy would be sufficient?

**Comment by ForNeVeR** [comment]
Ohhh, I am so sorry. Thanks for letting me know. Will update the workflow.
