### ISSUE TITLE
Error checking doesn't catch using <, > instead of the correct -lt, -gt in an if statement

### ISSUE THREAD

**Issue by joshuaking-madtech** [ant-druha/intellij-powershell#266]
When an conditional mistakenly uses the <, > instead of the PowerShell -lt -gt compare operators, subsequent suggestions/code completion break but the error isn't highlighted.

**Comment by ForNeVeR** [comment]
Could you please show some examples of contexts when the plugin gets it wrong?

It could be that our (very relaxed) grammar misses the errors, while PSES-powered completion gets it right.

In certain cases, `>` may be valid in same places where `-gt` is, while having totally different meanings. Say,
```powershell
 if (echo 12 > $null) { echo 1 } else { echo 2 }
 ```
 is a perfectly valid syntactic construct, even if a bit meaningless.
