### ISSUE TITLE
Auto-completion not available

### ISSUE THREAD

**Issue by safesparrow** [ant-druha/intellij-powershell#27]
Hi,

First of all, thanks a lot for the plugin!

I'm using the latest Rider EAP version (2019.2 EAP 5) and plugin version 2.0.2

When I edit a *.ps1 script, I don't get any auto-completion for built-in commands.
Simple "Write-Host" doesn't seem to be recognized by the editor.
I can run the script just fine from the IDE with the right results.
Is there any settings/environment change that would help with this?

Thanks again

**Comment by tarikweiss** [comment]
Hi,
for me it doesn't work too. I tried to install the powershell editor services manually and checked if the path for powershell is working correctly.

**Comment by slugmandrew** [comment]
Same here. Would be good if someone could look into this issue.

**Comment by ant-druha** [comment]
Hi guys. Could you please add 

```
com.intellij.plugin.powershell.lang.lsp.languagehost
#com.intellij.plugin.powershell.lang.lsp.languagehost
```

lines into Help | Debug Log Settings, restart IDE reproduce the problem and attach idea.log file (Help | Show Log in... action).
