### ISSUE TITLE
Powershell Core Support

### ISSUE THREAD

**Issue by su-rabbit** [ant-druha/intellij-powershell#28]
Powershell rebranded to [Powershell Core](https://docs.microsoft.com/ko-kr/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6)

And there are no option for run default run option with powershell.

Could you have plan for supporting this?

Thank you.!

**Comment by ant-druha** [comment]
Fixed in 2.0.7 version.
