### ISSUE TITLE
Have an option to send selected code to PowerShell console

### ISSUE THREAD

**Issue by young-zhang** [ant-druha/intellij-powershell#280]
You can send code to C# Interactive, or F# Interactive. In VSCode, one can send code to the PowerShell console with F8. However, this feature is missing from the PowerShell plugin for JetBrains.

**Comment by ForNeVeR** [comment]
I think this is a duplicate of #29.

**Comment by young-zhang** [comment]
Yes, this is indeed a dup of #29 - thanks for closing it for me.
