### ISSUE TITLE
Prompting for input?

### ISSUE THREAD

**Issue by lordmortis** [ant-druha/intellij-powershell#32]
When i try to prompt for input via "Read-Host" (or specifying parameters) I don't see the prompt displayed and the script hangs?

example:

```
param (
    [Parameter(Mandatory)]
    [string]$name = $( Read-Host "Migration Name" )
)
```

**Comment by machekku** [comment]
It seems that I have the same problem with $Host.UI.PromptForChoice()
Interestingly, pressing Enter accepts the default option, even though options and prompt were not visible.

**Comment by HeXDeMoN** [comment]
This is still an issue with latest version. Pretty much makes the entire module unusable for me.

**Comment by ForNeVeR** [comment]
It looks like it got better after #90, while still clunky.
