### ISSUE TITLE
How to run PSScriptAnalyzer

### ISSUE THREAD

**Issue by perostman** [ant-druha/intellij-powershell#34]
I do not seem to get the code inspection using PSScriptAnalyzer to work. 
PSSA is installed on my machine, but e g when choosing a file in IntelliJ and selecting the "Analyze -> Inspect Code" menu option, I don't get the same result as when running PSSA from the command line (in an example file, I get no errors in IntelliJ, but in PSSA, I get several remarks).

I have likely missed something obvious?

**Comment by bergmeister** [comment]
Hi, maintainer of [PSScriptanalyzer ](https://github.com/powershell/psscriptanalyzer)here 👋🏻
The intellij extension seems to use [PowerShellEditorServices](https://github.com/powershell/powershelleditorservices), which has a default set of hard-coded rules [here](https://github.com/PowerShell/PowerShellEditorServices/blob/765c76c930ffcc7f4727a2d1f1dd7ee3ac71e4ee/src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs#L64).
Therefore, when you run `Invoke-ScriptAnalyzer`, it runs all the available rules. 
You can use a [PSScriptAnalyzer settings file](https://github.com/powershell/psscriptanalyzer#settings-support-in-scriptanalyzer) if you want to control which rules to run or just run all of them (in this case just put `@{}` as the content of the file). PowerShellEditorServices supports settings files as well, but I am not sure if the intellij extension provides a way to exposes this API to the user. cc @ant-druha

**Comment by ForNeVeR** [comment]
Yep, IntelliJ has the ability to fetch and run particular inspections by name. We should implement that.

Currently, you only can run all the PSScriptAnalyzer inspections at once: find action **Run Inspection by Name** and type **PSScriptAnalyzer** into the name box.

Interestingly, for me it seems to work properly: the **Inspect Code** runs the same set of inspections, including the PSScriptAnalyzer.
<img width="939" alt="image" src="https://github.com/ant-druha/intellij-powershell/assets/92793/dde776dc-c1ee-4b94-9d45-c5bd536b1cb0">

For now, I consider this as working, and will open a new issue on running a particular inspection.
