### ISSUE TITLE
Run configuration keeps getting renamed when opening or editing.

### ISSUE THREAD

**Issue by codemasterover9000** [ant-druha/intellij-powershell#40]
Hi, 

I'm using this plugin to create a shared run configuration. The run configuration has a different name than the script being executed. But everytime I open the edit screen or at random the run configuration renames itself to the script filename. Resulting in a new .xml file in the .idea project directory.

My request is leave the run configuration name alone :)

Thanks

**Comment by codemasterover9000** [comment]
I think this is the problem: https://github.com/ant-druha/intellij-powershell/blob/6b91d466c1dd34b9f5b4a81ce9c286053cca1e45/src/main/java/com/intellij/plugin/powershell/ide/run/PowerShellRunSettingsEditor.java#L45

Should only set the name when the name is empty and a script is selected IMO.

**Comment by ant-druha** [comment]
@Dimi1010 thank you!
