### ISSUE TITLE
How to create a new project

### ISSUE THREAD

**Issue by WebTiger89** [ant-druha/intellij-powershell#41]
How can I create a new project. It's not documented anywhere. And is it possible to set breakpoints?

**Comment by kevinholtkamp** [comment]
You could use the [normal powershell way to do breakpoints](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/how-to-debug-scripts-in-windows-powershell-ise?view=powershell-7.2)

**Comment by ForNeVeR** [comment]
> How can I create a new project.

So far, the plugin doesn't support creating any sort of "PowerShell-only" projects.

If you need one, you may just start from an empty project in the new project wizard, and then just add `.ps1` files in any project directories.

> And is it possible to set breakpoints?

Not yet, but feel free to watch for #19. This is under consideration.
