### ISSUE TITLE
PowerShell + Docker

### ISSUE THREAD

**Issue by milgevskiy** [ant-druha/intellij-powershell#46]
I have the next error on trying to run configuration based on PowerShell.

> @digitalkyc/ZZZ@1.0.4 build D:\Projects\XXX\YYY\Sources\Web\src\Integrations\ZZZ
> tsc
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

My ps1 script builds docker file which in turn ends with next command:
`CMD [ "npm","run", "watch" ]`

package.json content:
```
...
"scripts": {
    "watch": "webpack -w"
  },
...
```

**Comment by ForNeVeR** [comment]
I believe this should be fixed after #90.
