### ISSUE TITLE
Would like to specify which PowerShell version is used for debugging

### ISSUE THREAD

**Issue by CaptainCrewe** [ant-druha/intellij-powershell#47]
Just starting in with Rider and developing PowerShell scripts using that (since we've lost the PowerShell IDE for now at least).

I see that if I run a script, the Run tab opens and shows C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe as the version to which my script is passed. Ideally, I'd like this to default to PowerShell 7 (the same as I've configured Rider to use as its Terminal).

Is that something I can adjust in an underlying file? I don't see any option in the Run Configuration to set a different version of PowerShell.

Many thanks indeed for your valuable contribution.

**Comment by ant-druha** [comment]
IDE uses the first `powershell.exe` or `pwsh.exe` executable which is encountered in the `PATH` environment variable. So until this request is fixed you may try to specify the executable path to powershell 7 earlier in `PATH` than other powershell versions. Does it help?

**Comment by CaptainCrewe** [comment]
Sounds a reasonable workaround.  I'll give it a go.

Thank you.

**Comment by ant-druha** [comment]
Fixed in 2.0.7 version.

**Comment by CaptainCrewe** [comment]
Many thanks indeed.  That makes the plugin more flexible and easier to use.  

It's a wonderful plugin - thank you for providing it to the community.

Best wishes
