### ISSUE TITLE
Support ternary conditional operator

### ISSUE THREAD

**Issue by rzippo** [ant-druha/intellij-powershell#52]
[Powershell 7](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-70?view=powershell-7.1) introduced ternary conditional operators, i.e.

`$value = $condition ? "a" : "b"`

Although the plugin does not recognize it, and highlights the `?` as an unexpected token.

**Comment by ant-druha** [comment]
This is actually highlighted by the PSAnalyzer inspection. It uses the PowerShell version found in the `PATH` to run the inspections. So if the PowerShell version found is lower than 7 - it will be reported as error. It should be fixed after adding the ability to choose the global PowerShell version: #28

**Comment by ant-druha** [comment]
Fixed in 2.0.7 version.
