### ISSUE TITLE
Run configuration working directory and relative paths

### ISSUE THREAD

**Issue by Krande** [ant-druha/intellij-powershell#63]
Hi,

as requested here is some further explaining of my comments made in #22
Note I am using Windows 10 and pycharm 2021.1.2 professional.

When I initially created my config file (leaving everything blank as shown below) 

![image](https://user-images.githubusercontent.com/9642232/120799843-86cb1600-c53f-11eb-81ba-bad3370e579c.png)

it creates a config file with the following content

```xml
<component name="ProjectRunConfigurationManager">
    <configuration default="false" name="test_script.ps1" type="PowerShellRunType" factoryName="PowerShell"
                   scriptUrl="$PROJECT_DIR$/test_rel_ps_path/test_script.ps1" workingDirectory="C:\Users\Kristoffer"
                   executablePath="$PROJECT_DIR$/../../../Windows/System32/WindowsPowerShell/v1.0/powershell.exe">
        <envs/>
        <method v="2"/>
    </configuration>
</component>
```

Which automatically inserts my windows user profile directory, even though default project directory is set to the following

![image](https://user-images.githubusercontent.com/9642232/120800015-c691fd80-c53f-11eb-9b96-116298bf5993.png)

and my test_script.ps1 is just

```powershell
$a = Get-Location
Write-Output $a
```

which returns

![image](https://user-images.githubusercontent.com/9642232/120800588-68b1e580-c540-11eb-8f70-f72be6c8cd43.png)

if I try to set the work dir to its relative parent directory like so

![image](https://user-images.githubusercontent.com/9642232/120802587-e37c0000-c542-11eb-8d65-2f3131a774e5.png)

I end up with a dir inside my pycharm installation directory
![image](https://user-images.githubusercontent.com/9642232/120802633-f2fb4900-c542-11eb-907b-254d748546bf.png)

However, it works as intended whenever I pass an absolute path 
![image](https://user-images.githubusercontent.com/9642232/120802744-13c39e80-c543-11eb-9927-4fd2b90752d8.png)

If I try to manually define $PROJECT_DIR$:
![image](https://user-images.githubusercontent.com/9642232/120802329-9ef06480-c542-11eb-8568-a0217e380bd9.png)

I end up with the following error
![image](https://user-images.githubusercontent.com/9642232/120802288-90a24880-c542-11eb-9d46-29f0ed425f8a.png)

So from what I can tell the leaving the working directory blank returns the user directory and relative paths are relative to a folder inside the pycharm installation folder. 

Could it be a bug in pycharm or is there something that can be done in the plugin or is it simply me not understanding how it all connects? :)

Best Regards
Kristoffer

**Comment by ForNeVeR** [comment]
> If I try to manually define $PROJECT_DIR$:
> ![image](https://user-images.githubusercontent.com/9642232/120802329-9ef06480-c542-11eb-8568-a0217e380bd9.png)
> 
> I end up with the following error
> ![image](https://user-images.githubusercontent.com/9642232/120802288-90a24880-c542-11eb-9d46-29f0ed425f8a.png)

I am not sure if this is technically a bug or not (the path variable handling in run configurations is kinda wild in the IntelliJ core), but one thing I can tell is that this behavior has been fixed in 2.0.8, by commit 7b50d35302e0601f231a8018b64dee2e8358aca0. And now it works well.

Thank you for very useful feedback; everything else from this issue, I believe, will be addressed by the solution proposed in #22.
