### ISSUE TITLE
Powershell script hangs when started from Run Configuration with missing mandatory parameter.

### ISSUE THREAD

**Issue by Dimi1010** [ant-druha/intellij-powershell#70]
The current PowerShell scripts when ran with the default run configuration will run in interactive mode.

In interactive mode, PowerShell upon encountering a missing mandatory parameter, will prompt the user to input that parameter, which the run window does not support at the moment, and this causes the process hanging that can only be resolved by terminating it.

A potential fix is to run PowerShell in non-interactive mode, when starting from a run configuration, by adding "-NonInteractive" to the command parameters, as that would cause the script to terminate with missing mandatory parameter exception instead.

It would be nice if the "-NonInteractive" parameter be added to the default PowerShell run configuration template of the plugin.

Tested on Pycharm 2021.2.1

Reproducable code:

MandatoryParamDeadlock.ps1
```
param(
    # Mandatory Demo Parameter
    [Parameter(Mandatory)]
    [string]
    $DemoMandatoryParameter
)

Write-Host $DemoMandatoryParameter
```

Hanging Run Configuration:
![image](https://user-images.githubusercontent.com/20269350/127770433-e3746b10-0673-4e64-b238-c22e85a51d92.png)

Fixed Run Configuration:
![image](https://user-images.githubusercontent.com/20269350/127770443-cf64b0ee-fbb0-4aa8-85e2-eb633452fe4d.png)

**Comment by ForNeVeR** [comment]
This seems to be fixed by #90.
