### ISSUE TITLE
how can i change what powershell version is used to run the scripts

### ISSUE THREAD

**Issue by footdabmommy** [ant-druha/intellij-powershell#71]

**Comment by Dr-Electricity** [comment]
it says here that you can change the powershell version used to execute the powershell scripts you write
![image](https://user-images.githubusercontent.com/86848983/128881423-a439687c-664c-4429-9c1f-af09101b64c7.png)
but i cant find from where can i change it
im on the latest version of intellij idea community and the latest version of this plugin

**Comment by ant-druha** [comment]
Globally:
![image](https://user-images.githubusercontent.com/3117044/128883867-df2e7d04-fd40-4062-b0fb-34206fd49d3f.png)

For run configuration:
![image](https://user-images.githubusercontent.com/3117044/128883793-67e87ccb-2464-47bf-8579-c2c185f35bc7.png)
