### ISSUE TITLE
Exception thrown when plugin is enabled but no powershell is found in the path

### ISSUE THREAD

**Issue by wheelerlaw** [ant-druha/intellij-powershell#76]
The plugin throws an unrecoverable exception when PowerShell is not found in the path:

![image](https://user-images.githubusercontent.com/3081566/141152389-7a5cc396-af6c-4bf5-8d99-84187e555ef2.png)

Instead, the plugin should fail Gracefully and not be required to be disabled if Powershell cannot be found in the path.

**Comment by mikeschinkel** [comment]
Exactly. I am using JetBrains IDEs on macOS to develop PowerShell scripts that are running in a VirtualBox-hosted Windows VM. I would like access to use this plugin even though PowerShell is not directly installed on my computer.

**Comment by pavel-alay** [comment]
I have installed pwsh under `/usr/local/bin/pwsh` but the plugin crashes with the executable not found anyway.

**Comment by wheelerlaw** [comment]
@ant-druha this is still a major issue

**Comment by ant-druha** [comment]
I'm sorry it took so long. I prepared a fix candidate version. Could you please test it — if this works for you? Thank you!

[PowerShell-2.0.10.zip](https://github.com/ant-druha/intellij-powershell/files/8140403/PowerShell-2.0.10.zip)

**Comment by wheelerlaw** [comment]
> I'm sorry it took so long. I prepared a fix candidate version. Could you please test it — if this works for you? Thank you!
> 
> [PowerShell-2.0.10.zip](https://github.com/ant-druha/intellij-powershell/files/8140403/PowerShell-2.0.10.zip)

Yes, that fixes the issue. Thank you!

**Comment by ecarmen16** [comment]
This fixes the crash but *not* the plugin correctly detecting PowerShell's installation path/version on Ubuntu. Should this be configured by hand somewhere?

**Comment by ant-druha** [comment]
@ecarmen16 please try Settings (Preferences on macOS) | Languages & Frameworks | PowerShell | **PowerShell executable path**.

**Comment by ecarmen16** [comment]
So close! Here's the next hurdle:
![image](https://user-images.githubusercontent.com/28810586/156452792-400a5140-accb-4d1c-b316-f3c7c0c9cb92.png)

This is where we are running into the other open issue [for Linux users.](https://github.com/ant-druha/intellij-powershell/issues/79)
