### ISSUE TITLE
Pasting into .ps1 file removes indentation

### ISSUE THREAD

**Issue by kevinholtkamp** [ant-druha/intellij-powershell#84]
When i copy code from any file (also from a .ps1 file) and paste it into a .ps1 file, all indentation is removed

**Comment by ForNeVeR** [comment]
This is an IntelliJ feature called **Reformat on paste**. You can either:
- disable it in the IDE settings
- report cases when it misbehaves separately (to this issue tracker; please do!)
- use **Paste as Plain Text** (`Ctrl+Alt+Shift+V` in the IntelliJ keymap on Windows)
