### ISSUE TITLE
always insert a new #> line when in comment mode

### ISSUE THREAD

**Issue by yhjhoo** [ant-druha/intellij-powershell#94]
Original 

```
    <#
    .SYNOPSIS

    kcurrent
    display current kubernets namespaces

    
    #>
```
whenever I input a new line, it became following

<#
    .SYNOPSIS

    kcurrent
    display current kubernets namespaces

    
     #>
     #>
    #>

**Comment by ForNeVeR** [comment]
Duplicate of #35. It is in my short list of issues I hope to start working on.
