### ISSUE TITLE
powershell ForEach Reduce Syntax not interpreted as usage

### ISSUE THREAD

**Issue by modellking** [ant-druha/intellij-powershell#96]
***What steps will reproduce the issue?***

```powershell
(1..3) | ForEach-Object {
    $Hashes = ""
} {
    $Hashes += "Some-String "
} {
    $Hashes
}
```

***What is the expected result?***

No Issue being detected. $Hashes is read and modified in the loop and is being passed on due to the third bracket. (Yes this is apparently not documented)

***What happens instead?***

*line 2 `$Hashes` gets marked with "The variable Hashes is assigned but never used."*

**Comment by ForNeVeR** [comment]
This is not a plugin issue but an issue of PSScriptAnalyzer, the analyzer issue we use.

I have reported it upstream: https://github.com/PowerShell/PSScriptAnalyzer/issues/1942.
